[launcher]
executable_file = 'Client-Win64-Shipping.exe'
cmd_line_args = '-fileopenlog'
current_dir = 'C:/Users/Administrator/Documents/GitHub/Server/Client/Client/Binaries/Win64'
dll_list = ['C:/Users/Administrator/Documents/GitHub/Server/Client/Client/Binaries/Win64/wicked-waifus-win-cn_beta_2_5_1-regular.dll']

[environment]
#vars = ['TESTVAR1=AAAAAA', 'TESTVAR2=AAAAAA']
#use_system_env = true
#environment_append = false